// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfKyJ6HSEOcT4v8y1WBi2A150aAkD5IDU',
    appId: '1:276085447357:web:70af53e4deac073f53f5d4',
    messagingSenderId: '276085447357',
    projectId: 'flutterdatabase-d0392',
    authDomain: 'flutterdatabase-d0392.firebaseapp.com',
    storageBucket: 'flutterdatabase-d0392.appspot.com',
    measurementId: 'G-268DWE6RR4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCF3Y4BqqnTwFKO117_2d3aElBoBiRxCF4',
    appId: '1:276085447357:android:25b2425d8120e8fc53f5d4',
    messagingSenderId: '276085447357',
    projectId: 'flutterdatabase-d0392',
    storageBucket: 'flutterdatabase-d0392.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOx2oCJIJk3dpymH_m2xbqrvDyYLo1DVg',
    appId: '1:276085447357:ios:d3b6c5c193eed78553f5d4',
    messagingSenderId: '276085447357',
    projectId: 'flutterdatabase-d0392',
    storageBucket: 'flutterdatabase-d0392.appspot.com',
    iosBundleId: 'com.example.flutterDatabase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOx2oCJIJk3dpymH_m2xbqrvDyYLo1DVg',
    appId: '1:276085447357:ios:d3b6c5c193eed78553f5d4',
    messagingSenderId: '276085447357',
    projectId: 'flutterdatabase-d0392',
    storageBucket: 'flutterdatabase-d0392.appspot.com',
    iosBundleId: 'com.example.flutterDatabase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfKyJ6HSEOcT4v8y1WBi2A150aAkD5IDU',
    appId: '1:276085447357:web:d5977a04a5e1f75953f5d4',
    messagingSenderId: '276085447357',
    projectId: 'flutterdatabase-d0392',
    authDomain: 'flutterdatabase-d0392.firebaseapp.com',
    storageBucket: 'flutterdatabase-d0392.appspot.com',
    measurementId: 'G-L8S9RMPLZ5',
  );

}